databases:
  name: postgres
  ipAllowList: []

services:
   type: pserv
   name: pgbouncer
   env: docker
   plan: standard
   repo: https://github.com/render-oss/docker-pgbouncer
  envVars:
    buildCommand: "./bin/render.build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    key: RAILS_MASTER_KEY
    sync: false
    key: DATABASE_URL
    fromDatabase:
      name: postgres
      property: connectionString
  plan: free
  maxMemoryPolicy: noeviction

